import sqlite3
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# Set page configuration
st.set_page_config(
    page_title="SaaS Churn & Retention Analytics",
    page_icon="📊",
    layout="wide"
)

# Title & Description
st.title("📊 SaaS Customer Churn & Retention Dashboard")
st.markdown("""
An end-to-end analytical dashboard powered by Machine Learning and SQLite cohort queries.
Use the sidebar filters to segment churn risk and analyze customer retention profiles.
""")


# Function to load data from SQLite database
@st.cache_data
@st.cache_data
def load_data():
  # Try loading CSV first, fall back to SQLite if needed
  try:
    df = pd.read_csv("processed_churn_risk.csv")
  except Exception:
    conn = sqlite3.connect("churn_analysis.db")
    df = pd.read_sql("SELECT * FROM customer_churn_risk", conn)
    conn.close()

  # Safely handle Churn_Probability column naming variations
  prob_col = None
  for col in ["Churn_Probability", "churn_probability", "churn_risk", "Risk"]:
    if col in df.columns:
      prob_col = col
      break

  if prob_col:
    df["Churn_Probability"] = df[prob_col]
  else:
    df["Churn_Probability"] = 0.0

  # Auto-generate Risk_Category if missing
  if "Risk_Category" not in df.columns:

    def assign_risk(prob):
      if prob >= 0.7:
        return "High Risk"
      elif prob >= 0.3:
        return "Medium Risk"
      else:
        return "Low Risk"

    df["Risk_Category"] = df["Churn_Probability"].apply(assign_risk)  
  # Loads directly from the CSV generated by churn_model.py
  return df


# Load data
df = load_data()

# ---------------------------------------------------------
# Sidebar Filters
# ---------------------------------------------------------
st.sidebar.header("Filter Customers")

# Contract Filter
contract_options = ['All'] + list(df['Contract'].unique())
selected_contract = st.sidebar.selectbox("Contract Type", contract_options)

# Risk Category Filter
risk_options = ['All'] + list(df['Risk_Category'].unique())
selected_risk = st.sidebar.selectbox("Risk Category", risk_options)

# Payment Method Filter
payment_options = ['All'] + list(df['PaymentMethod'].unique())
selected_payment = st.sidebar.selectbox("Payment Method", payment_options)

# Filter Dataframe
filtered_df = df.copy()

if selected_contract != 'All':
  filtered_df = filtered_df[filtered_df['Contract'] == selected_contract]

if selected_risk != 'All':
  filtered_df = filtered_df[filtered_df['Risk_Category'] == selected_risk]

if selected_payment != 'All':
  filtered_df = filtered_df[filtered_df['PaymentMethod'] == selected_payment]

# ---------------------------------------------------------
# Key Metrics / KPIs
# ---------------------------------------------------------
col1, col2, col3, col4 = st.columns(4)

total_customers = len(filtered_df)
avg_churn_risk = (
    filtered_df['Churn_Probability'].mean() * 100
    if total_customers > 0
    else 0
)
high_risk_count = len(filtered_df[filtered_df['Risk_Category'] == 'High Risk'])
total_mrr = filtered_df['MonthlyCharges'].sum()

col1.metric("Total Customers", f"{total_customers:,}")
col2.metric("Avg Churn Risk", f"{avg_churn_risk:.1f}%")
col3.metric("High-Risk Customers", f"{high_risk_count:,}")
col4.metric("Total Monthly Revenue", f"${total_mrr:,.2f}")

st.divider()

# ---------------------------------------------------------
# Visualizations Row 1
# ---------------------------------------------------------
c1, c2 = st.columns(2)

with c1:
  st.subheader("Customer Risk Segmentation")
  risk_counts = (
      filtered_df['Risk_Category'].value_counts().reset_index()
  )
  risk_counts.columns = ['Risk_Category', 'Count']
  fig_risk = px.pie(
      risk_counts,
      names='Risk_Category',
      values='Count',
      color='Risk_Category',
      color_discrete_map={
          'Low Risk': '#2ecc71',
          'Medium Risk': '#f1c40f',
          'High Risk': '#e74c3c',
      },
      hole=0.4,
  )
  st.plotly_chart(fig_risk, use_container_width=True)

with c2:
  st.subheader("Churn Risk by Tenure")
  fig_tenure = px.scatter(
      filtered_df,
      x='tenure',
      y='Churn_Probability',
      color='Contract',
      hover_data=['customerID', 'MonthlyCharges'],
      labels={
          'tenure': 'Tenure (Months)',
          'Churn_Probability': 'Churn Probability',
      },
      opacity=0.7,
  )
  st.plotly_chart(fig_tenure, use_container_width=True)

# ---------------------------------------------------------
# Visualizations Row 2
# ---------------------------------------------------------
c3, c4 = st.columns(2)

with c3:
  st.subheader("Monthly Charges Distribution by Churn Status")
  fig_charges = px.histogram(
      filtered_df,
      x='MonthlyCharges',
      color='Churn',
      barmode='overlay',
      labels={'MonthlyCharges': 'Monthly Charges ($)'},
      color_discrete_map={'Yes': '#e74c3c', 'No': '#3498db'},
  )
  st.plotly_chart(fig_charges, use_container_width=True)

with c4:
  st.subheader("Churn Rate by Payment Method")
  pm_churn = (
      filtered_df.groupby('PaymentMethod')['Churn_Probability']
      .mean()
      .reset_index()
  )
  pm_churn['Churn_Probability'] = pm_churn['Churn_Probability'] * 100
  fig_pm = px.bar(
      pm_churn,
      x='PaymentMethod',
      y='Churn_Probability',
      labels={
          'PaymentMethod': 'Payment Method',
          'Churn_Probability': 'Avg Churn Risk (%)',
      },
      color='Churn_Probability',
      color_continuous_scale='Reds',
  )
  st.plotly_chart(fig_pm, use_container_width=True)

# ---------------------------------------------------------
# Data Table View
# ---------------------------------------------------------
st.divider()
st.subheader("Customer Churn Risk Table")
st.dataframe(
    filtered_df[
        [
            'customerID',
            'Contract',
            'tenure',
            'MonthlyCharges',
            'Churn_Probability',
            'Risk_Category',
        ]
    ].head(100),
    use_container_width=True,
)